
name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  createIssue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          JIRA_API_HOST: ${{secrets.JIRA_API_HOST}}
          JIRA_API_TOKEN: ${{secrets.JIRA_API_TOKEN}}
          JIRA_EMAIL: ${{secrets.JIRA_EMAIL}}
          TRIGGER_LABEL: jira
          JIRA_PROJECT_ID: RV
          JIRA_ISSUE_NAME: #3 Story
