on:
  push

name: Test Transition Issue

jobs:
  test-transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Login
      uses: ravitejVarada1/ga-jira-integration-main@master
      env:
        JIRA_BASE_URL: https://rvarada.atlassian.net/browse/RV
        JIRA_USER_EMAIL: ${{ secrets.JIRA_EMAIL }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

    - name: Create Jira issue on job failure
      uses: ravitejVarada1/ga-jira-integration-main@master
      with:
        project: Varada
        issuetype: Build
        summary: Build failed for ${{ github.repository }}